project_name: tpl
release:
  github:
    owner: zerok
    name: tpl
builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./cmd/tpl
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: tpl
archives:
  - format: tar.gz
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
    - README.md
    - LICENSE
snapshot:
  name_template: SNAPSHOT-{{ .Commit }}
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
